feat: add CFBundleShortVersionString attribute
SonicCloudOrg/sonic-ios-bridge pull request #52
Opened 2022-12-30 13:56 UTC by viz1997

**在提出此拉取请求时，我确认了以下几点（保存后请点击复选框）：**

- [ ] 标题为fix、feat或doc开头
- [ ] 我已检查没有与此请求重复的拉取请求。
- [ ] 我已经考虑过，并确认这份呈件对其他人很有价值。
- [ ] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。

**填写PR内容：**

2022-12-30 14:40 UTC, ZhouYixun commented on go.mod
> +// replace github.com/SonicCloudOrg/sonic-ios-bridge => ./sonic-ios-bridge
这个注释可以去掉

2022-12-30 14:41 UTC, ZhouYixun commented on src/entity/application.go
>  	CFBundleVersion     string `json:"version"`
驼峰命名法，我建议使用shortVersion哦

2022-12-30 14:46 UTC, ZhouYixun requested changes
感谢您的贡献，需调整的内容如上，有疑问可以互相讨论

2022-12-30 17:42 UTC, ZhouYixun approved these changes
感谢您的贡献，可以发送您的快递收发地址到soniccloudorg@163.com，我们会发出贡献证书

2022-12-30 17:45 UTC, ZhouYixun commented on cmd/app/list.go
>  				if showIcon {
我仔细想了一下，这里应该不对，有的App CFBundleShortVersionString就是空字符串的，可以不进行判断，然后`CFBundleShortVersionString string `json:"shortVersion"``应该加上omitempty

2022-12-30 17:45 UTC, ZhouYixun requested changes
还有一个地方调整

2022-12-30 17:50 UTC, ZhouYixun commented on cmd/app/list.go
>  				if showIcon {
其实这里判断是不是有点不对劲 @aoliaoaoaojiao

2022-12-30 18:05 UTC, aoliaoaoaojiao commented on cmd/app/list.go
>  				if showIcon {
如果你是怕出现CFBundleShortVersionString为空这种情况，那你应该用a.CFBundleIdentifier != "" || a.CFBundleDisplayName != "" || a.CFBundleShortVersionString != "" || a.CFBundleVersion != ""

2022-12-31 08:49 UTC, ZhouYixun commented on cmd/app/list.go
>  				if showIcon {
@viz1997 那按照楼上的回复修改一下吧

2022-12-31 12:41 UTC, ZhouYixun approved these changes
感谢贡献，允许合入

2022-12-31 12:45 UTC, merged